### ISSUE TITLE
cannot login

### ISSUE THREAD

**Issue by gucio321** [km1chno/overleaf-sync-rs#28]
```console
[~ (0) ]$ olsync login
[!] Failed to log in with the following error:
 |  Failed to obtain session info from login browser
[~ (0) ]$ 
```

OS: I use arch btw
browser: I have brave browser (set as default) and firefox

```version
[~ (0) ]$ olsync --version
olsync 0.3.0
```

**Comment by katzper-michno** [comment]
Unfortunately, the script can only open `google-chrome` for login, which is listed as [dependency](https://github.com/km1chno/overleaf-sync-rs?tab=readme-ov-file#-dependencies), so you have to install it to use `overleaf-sync-rs`.

The reason for that is that [headless_chrome crate](https://docs.rs/crate/headless_chrome/latest) is used for spawning browser window for login. It would be great to somehow support other browsers, but I didn't find an easy way to do it.

**Comment by katzper-michno** [comment]
on arch, I think https://aur.archlinux.org/packages/google-chrome should work

**Comment by gucio321** [comment]
ok, thank you. I think I din't read things carefully enough :smile:
I have 2 questions then:
1. brave is on chromium, so its support should be similar to chrome (?)
2. who is the host of `aur`? I think it might list google-chrome as its dependency

**Comment by gucio321** [comment]
@km1chno sorry for unrelated question but I don't want to open another issue:
```
[✔] Obtained session info from cache.
[!] Failed to fetch project details.                      
[!] Failed to push some files with the following error:
 |  Failed to obtain project info for project 67168c7dc813e002f320e4e4.
```
